language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

notifications:
  email:
    recipients:
      - joshua.moody@xamarin.com
      - chris.fuentes@xamarin.com
      - tobias.roikjer@xamarin.com
    on_success: change
    on_failure: always

script:
  - bin/ci/travis/run.sh
